# Select a base image
FROM  node:18

# Create a directory  and go to the directory 
WORKDIR /app

# Copy the package.json file to my current directory to install the necessary dependence  
COPY package*.json ./

# Install the dependence. ci: clean install, --omit=dev: do not install dev dependencies, npm cache clean --force: clean the npm cache to reduce image size
RUN npm ci && npm cache clean --force
# Copy other files to my current directory
COPY . .

# Open the port for the express server
EXPOSE 3001
# ENV MONGODB_URI=mongodb+srv://marzveer123:PLwnGldtAXvSTQp7@users.y3oq1.mongodb.net/AlmaariOrganized


CMD ["npm","run","dev"]